import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidemenu from "@/components/sidemenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="drawer md:drawer-open">
          <input id="my-drawer" type="checkbox" className="drawer-toggle" />

          {/* Sidebar */}
          <div className="drawer-side">
            <label
              htmlFor="my-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
              <Sidemenu />
            </ul>
          </div>

          {/* Main page content */}
          <div className="drawer-content">
            <label
              htmlFor="my-drawer"
              className="btn btn-primary drawer-button md:hidden"
            >
              Open drawer
            </label>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
